FROM node:24.8.0-alpine3.22 AS builder

WORKDIR /home/saundersp/portfolio

COPY public public
COPY src src
COPY package.json package-lock.json ./

RUN npm i && npm run build && rm -r node_modules

FROM node:24.8.0-alpine3.22

RUN npm i -g http-server

USER node

WORKDIR /home/saundersp/portfolio

COPY --from=builder /home/saundersp/portfolio/build build
COPY certificates /home/saundersp/portfolio/certificates

EXPOSE 443

CMD ["http-server", "build", "-p", "443", \
	"-S", "-C", "certificates/cert.pem", \
	"-K", "certificates/privkey.pem"]
