services:
  no_ssl:
    image: saundersp/portfolio_no_ssl
    pull_policy: never
    build:
      dockerfile: Dockerfile.no_ssl
    ports:
      - 80:80

  ssl:
    image: saundersp/portfolio_ssl
    pull_policy: never
    build:
      dockerfile: Dockerfile._ssl
    ports:
      - 443:443
