FROM node:22.3.0-alpine3.20

WORKDIR /home/saundersp/portfolio

COPY public public
COPY src src
COPY package.json package-lock.json ./
COPY certificates certificates

RUN npm i -g http-server && npm i && npm run build

EXPOSE 443

CMD ["http-server", "build", "-p", "443", \
	"-S", "-C", "certificates/cert.pem", \
	"-K", "certificates/privkey.pem"]
